version: '3.1'

services:

  camelcrafts-db:
    container_name: camelcrafts-db
    image: postgres
    restart: always
    ports:
      - "9432:5432"
    environment:
      POSTGRES_USER: camelcrafts
      POSTGRES_PASSWORD: secretkey
      POSTGRES_DB: camelcraft

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@novi.nl
      PGADMIN_DEFAULT_PASSWORD: admin
